apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest-fitness
      version: green
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: green
    spec:
      containers:
      - name: aceest-fitness
        image: krishnakumar2022us70010/aceest-fitness:v2.0
        ports:
        - containerPort: 5000